import { Project } from '@langri-sha/projen-project'

// Projen owns the repository root only. Every file inside a module directory
// is written by the Dagger TypeScript SDK — `dagger develop` regenerates
// `package.json`, `tsconfig.json`, `yarn.lock`, `.gitignore`, `.gitattributes`
// and `sdk/` from its own templates, so anything Projen synthesized there
// would be reverted on the next run and re-synthesized on the one after.
//
// The modules stay out of the pnpm workspace for the same reason: each one is
// an independently installable Dagger module that the runtime builds with
// Yarn inside its own container. `packages: []` below is that decision, not
// an oversight.
const project = new Project({
  name: 'dagger',
  package: {
    authorEmail: 'filip.dupanovic@gmail.com',
    authorName: 'Filip Dupanović',
    authorOrganization: false,
    authorUrl: 'https://langri-sha.com',
    bugsUrl: 'https://github.com/langri-sha/dagger/issues',
    copyrightYear: '2026',
    description:
      'Reusable Dagger TypeScript modules for personal infrastructure',
    homepage: 'https://langri-sha.com',
    license: 'MIT',
    licensed: true,
    minNodeVersion: '24.16.0',
    repository: 'langri-sha/dagger',
    type: 'module',

    devDeps: [
      '@langri-sha/prettier@^0.4.6',
      '@langri-sha/projen-project@*',
      '@types/node@24.13.3',
      'prettier@3.9.6',
      'prettier-plugin-ini@1.3.0',
      'tsx@4.23.12',
      // Matches the version the Dagger TypeScript SDK installs into every
      // module, so `check:types` typechecks against the same compiler the
      // runtime uses. Held at ^5 by a Renovate rule below.
      'typescript@5.9.3',
    ],
  },
  codeowners: {
    '*': '@langri-sha',
  },
  editorConfig: {},
  lintSynthesized: {},
  pnpmWorkspace: {
    minimumReleaseAgeExclude: ['@langri-sha/*'],
    allowBuilds: {
      '@swc/core': false,
      esbuild: false,
      'unrs-resolver': false,
    },
  },
  prettier: {
    ignorePatterns: [
      // Written by `dagger develop`, in its own formatting. Prettier and the
      // SDK would rewrite these past each other on every run.
      '*/package.json',
      '*/tsconfig.json',
      '*/sdk/',
    ],
  },
  readme: {
    filename: 'readme.md',
  },
  renovate: {
    packageRules: [
      {
        description: 'Packages published from the langri-sha/projen monorepo',
        groupName: 'langri-sha projen toolchain',
        groupSlug: 'langri-sha-projen',
        matchSourceUrls: ['https://github.com/langri-sha/projen'],
      },
      {
        description: 'Install our own packages without waiting them out',
        matchPackageNames: ['@langri-sha/**'],
        minimumReleaseAge: null,
      },
      {
        description:
          'Install our own GitHub Actions and Terraform modules without waiting them out',
        matchPackageNames: ['langri-sha/**'],
        minimumReleaseAge: null,
      },
      {
        description:
          'Move every module off one engine release at a time, the way `dagger develop` writes them',
        groupName: 'Dagger engine',
        groupSlug: 'dagger-engine',
        matchDepNames: ['dagger/dagger'],
      },
      {
        description:
          'The Dagger SDK writes the module manifests, including the TypeScript pin. Upgrades here are reverted by the next `dagger develop`',
        matchManagers: ['npm'],
        matchFileNames: ['*/package.json'],
        enabled: false,
      },
      {
        description:
          'Track the TypeScript major the Dagger SDK installs into the modules, so `check:types` keeps using the runtime compiler',
        matchManagers: ['npm'],
        matchPackageNames: ['typescript'],
        allowedVersions: '^5',
      },
    ],
    customManagers: [
      {
        // Renovate has no manager for `dagger.json`. The `v` prefix sits
        // outside the capture group so the replacement leaves it in place.
        customType: 'regex',
        datasourceTemplate: 'github-releases',
        depNameTemplate: 'dagger/dagger',
        managerFilePatterns: ['/(^|/)dagger\\.json$/'],
        matchStrings: ['"engineVersion":\\s*"v(?<currentValue>[^"]+)"'],
        extractVersionTemplate: '^v(?<version>.+)$',
      },
    ],
  },
})

project.package?.addField('private', true)
project.package?.addField('packageManager', 'pnpm@12.3.4')
project.package?.addEngine('pnpm', '>= 11.0.0')

// `sdk/` is regenerated by `dagger develop` and never committed. The modules
// each ignore their own, this catches a module that has not been developed
// since it was scaffolded.
project.gitignore.addPatterns('**/sdk/', '*.tsbuildinfo')

project.package?.setScript('format', 'prettier --write .')
project.package?.setScript('format:check', 'prettier --check .')

// A bare `for` loop exits with the status of its last iteration, which would
// report success while an earlier module failed. Both tasks run every module
// and then fail if any of them did.
project.addTask('dagger:develop', {
  description: 'Regenerate sdk/ for every Dagger module',
  exec: 'status=0; for m in */dagger.json; do (cd "$(dirname "$m")" && dagger develop) || status=1; done; exit $status',
})

project.addTask('check:types', {
  description: 'Typecheck every Dagger module against its generated sdk/',
  exec: 'status=0; for m in */dagger.json; do tsc --noEmit -p "$(dirname "$m")" || status=1; done; exit $status',
})

project.gitattributes.addAttributes(
  'readme',
  'text=auto',
  'linguist-language=Markdown',
)

project.synth()
